# Generated by Django 3.2.4 on 2023-03-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230326_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
